/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_peSzL3aau",
    "aws_user_pools_web_client_id": "1mnpu61vce6opcmto6vnorohe5",
    "oauth": {}
};


export default awsmobile;
