/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_J29qzbR5M",
    "aws_user_pools_web_client_id": "54ckqeevfkjvvcd0vj6okbusq6",
    "oauth": {}
};


export default awsmobile;
